language: php

dist: trusty
php:
  - "7.1"
  - "7.0"
  - "5.6"
  - "5.5"
  - "5.4"
  - hhvm

matrix:
  include:
    - php: "5.3"
      dist: precise

before_script:
  - composer install -n --dev --prefer-source

script:
  - vendor/bin/phpcs --standard=PSR2 src
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" == "hhvm" ]; then vendor/bin/phpunit --verbose; fi;'
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then vendor/bin/phpunit --verbose --coverage-clover coverage.clover; fi;'

after_success:
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then wget https://scrutinizer-ci.com/ocular.phar; fi;'
  - bash -c 'if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php ocular.phar code-coverage:upload --format=php-clover coverage.clover; fi;'
